services:
  mysql:
    image: mysql:8.0.42
    container_name: turip-mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: turip_dev
      MYSQL_USER: turip
      MYSQL_PASSWORD: turip_pw
      TZ: Asia/Seoul
    ports:
      - "3306:3306"

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /home/ubuntu/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - /home/ubuntu/logs:/home/ubuntu/logs:ro
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
