spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:database

  sql:
    init:
      mode: always
      data-locations:
        - classpath:Region/region_data.sql
        - classpath:data.sql
        - classpath:yeoconam_gangwon_gyeongju_data.sql
        - classpath:yeoconam_ganwon_gangneung_data.sql
        - classpath:hachantour_gangwon_data.sql
        - classpath:jejueddy_gangwon_sokcho_data.sql
        - classpath:yeoconam_seoul_data.sql
        - classpath:jejueddy_posak_date.sql

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
