name: CI Build and Test, EC2 CD

on:
  push:
    branches: [ develop ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ develop ]
    paths:
      - 'backend/**'

jobs:
  build_and_test:
     runs-on: ubuntu-latest
     
     defaults:
      run:
        working-directory: backend
        
     steps: 
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Set up Gradle
       uses: gradle/actions/setup-gradle@v3
             
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew

     - name: Set up JDK 21
       uses: actions/setup-java@v4
       with:
         java-version: '21'
         distribution: 'temurin'
         cache: 'gradle'

     - name: Run Unit Tests
       run: ./gradlew test

     - name: Build Docker image
       run: |
         IMAGE_NAME=seaoniiii/turip-server:dev-${{ github.sha }}
         echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
         docker build -t $IMAGE_NAME backend/Dockerfile.dev ./backend

     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Push Docker image
       run: docker push ${{ env.IMAGE_NAME }}

  deploy:
    needs: build_and_test
    runs-on: [ self-hosted, turip-test-dev ]
    if: github.event_name == 'push'

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull and Run Docker container
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/turip-server:dev-${{ github.sha }}
          docker pull $IMAGE_NAME

          # 기존 컨테이너 정리
          docker stop turip-dev || true && docker rm turip-dev || true

          # 새 컨테이너 실행
          docker run -d --name turip-dev -p 8080:8080 \
            -e "SPRING_PROFILES_ACTIVE=dev" \
            $IMAGE_NAME
