name: CI Build and Test

on:
  pull_request:
    types: [closed] # Pull Request가 닫힐 때 아래 jobs가 실행
    branches: [ develop ]

jobs: # on 상황에서 수행할 작업들 정의
  build:
     runs-on: ubuntu-latest # GitHub 호스팅 러너 사용
     steps: 
     - name: Checkout code
       uses: actions/checkout@v4 # 저장소 코드 체크아웃

     - name: Set up Gradle
       uses: gradle/actions/setup-gradle@v3
       
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew

     - name: Set up JDK 21
       uses: actions/setup-java@v4
       with:
         java-version: '21'
         distribution: 'temurin'
         cache: 'gradle' # Gradle 캐싱 설정 (선택 사항, 빌드 속도 향상)
       
     - name: Build with Gradle
       run: ./gradlew clean build -x test # 테스트는 별도 스텝에서 실행하거나, 여기 포함 가능
  test:
     runs-on: ubuntu-latest # GitHub 호스팅 러너 사용
     needs: build # joba 끝난 후 실행
     steps:
     - name: Run Unit Tests
       run: ./gradlew test # 유닛 테스트 실행 (선택 사항, 빌드와 분리하여 명확성 확보)

  upload_jar:
     runs-on: ubuntu-latest # GitHub 호스팅 러너 사용
     steps:
     - name: Upload Jar
       uses: actions/upload-artifact@v4 # 빌드된 JAR 파일을 아티팩트로 업로드
       with:
         name: spring-boot-app # 아티팩트 이름
         path: build/libs/*.jar # 빌드된 JAR 파일 경로
         retention-days: 5 # 아티팩트 보존 기간 (선택 사항)
      
